config/routes.rb
Rails.application.routes.draw do
  get 'cards/index'

	resources :decks do
		resources :cards, except: [:index]
		post "/cards/:id", to: "cards#check_answer"
	end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck

	def check_answer answer
		answer.downcase == back.downcase
	end
end

app/models/deck.rb
class Deck < ActiveRecord::Base
	has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	before_filter :find_deck
	before_filter :find_card, except: [:new, :create]

	def new
		@card = @deck.cards.new
	end

	def create
		@card = @deck.cards.new(card_params)
		@card.save
		redirect_to @deck
	end

	def show
	end

	def check_answer
		guess = params[:card][:back]
		if @card.check_answer(guess)
			flash[:success] = "Correct!"
			redirect_to [@deck, @card]
		else
			flash[:notice] = "Incorrect!"
			redirect_to [@deck, @card]
		end
	end

	def edit
	end

	def update
		@card.update(card_params)
		redirect_to @deck
	end

	def destroy
		@card.destroy
		redirect_to @deck
	end

	private

	def card_params
		params.require(:card).permit(:front, :back)
	end

	def find_deck
		@deck = Deck.find_by_id(params[:deck_id])
	end

	def find_card
		@card = Card.find_by_id(params[:id])
	end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
	before_action :find_deck, only: [:show, :edit, :update, :destroy]

	def index
		@decks = Deck.all
	end

	def show
		@cards = @deck.cards
	end

	def new
		@deck = Deck.new
	end

	def create
		@deck = Deck.new(deck_params)
		@deck.save
		redirect_to @deck
	end

	def edit
	end

	def update
		@deck.update(deck_params)
		redirect_to decks_path
	end

	def destroy
		@deck.destroy
		redirect_to decks_path
	end

	private

	def find_deck
		@deck = Deck.find_by_id(params[:id])
	end

	def deck_params
		params.require(:deck).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
	def next_card(deck, card)
		attempt = deck.cards.sample
		attempt if attempt != card else next_card
	end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/cards/_form.html.erb
	<div>
		<%= form.label :front %>
		<%= form.text_field :front %>
	</div>
	<div>
		<%= form.label :back %>
		<%= form.text_field :back %>
	</div>

app/views/cards/edit.html.erb
<h1>Editing the <%= @card.front %> card</h1>
<div class="actions">
	<%= link_to "<< Back to #{@deck.name}", deck_path(@deck) %>
</div>
<div class="container">
<%= form_for [@deck, @card] do |form| %>
	<%= render form %>
	<%= form.submit "Update Card" %>
<% end %>
</div>

app/views/cards/new.html.erb
<h1>Create New Card for <%= @deck.name %></h1>
<div class="actions">
	<%= link_to "<< Back to #{@deck.name}", deck_path(@deck) %>
</div>
<div class="container">
<%= form_for [@deck, @card] do |form| %>
	<%= render form %>
	<%= form.submit "Create Card" %>
<% end %>
</div>

app/views/cards/show.html.erb
<h1><%= @card.front %></h1>
<div class="actions">
	<%= link_to "<< back to #{@deck.name} deck", deck_path(@deck) %>
</div>
<div class="container">
<% next_card = [@deck, @deck.cards.sample] %>
<% if flash.to_hash.include? "notice" %>
	<div class="answer">
		<h2>Nope! The correct answer was:</h2>
		<p><%= @card.back %></p>
		<%= link_to "Next Card >>", next_card %> 
	</div>
<% elsif flash.to_hash.include? "success" %>
	<div class="answer">
		<h2>Correct! Nice Job!</h2>
		<%= link_to "Next Card >>", next_card %>
	</div>
<% else %>
	<%= form_for "card" do |form| %>
		<div>
			<%= form.label :back, "Answer:" %>
			<%= form.text_field :back, value: nil %>
		</div>
		<%= form.submit "Submit Answer" %>
	<% end %>
<% end %>
</div>

app/views/decks/_form.html.erb
<div>
	<%= form.label :name %>
	<%= form.text_field :name %>
</div>

app/views/decks/edit.html.erb
<h1>Editing the <%= @deck.name %> deck</h1>
<div class="actions"><%= link_to "<< Back to Decks", decks_path %></div>
<div class="container">
<%= form_for @deck do |form| %>
	<%= render form %>
	<%= form.submit "Update Deck" %>
<% end %>
</div>

app/views/decks/index.html.erb
<h1>Viewing Decks</h1>
<div class="actions"><%= link_to "Create a new deck", new_deck_path %></div>
<div class="container">
<% @decks.each do |deck| %>
	<div>
		<%= link_to deck.name, deck %> &mdash; 
		<%= link_to "Edit", edit_deck_path(deck) %> 
		<%= link_to "Destroy", deck, data: { confirm: "Delete the #{deck.name} deck?" }, method: :delete %>
	</div>
<% end %>
</div>

app/views/decks/new.html.erb
<h1>Create a new deck</h1>
<div class="actions">
	<%= link_to "<< Back to Decks", decks_path %>
</div>
<div class="container">
<%= form_for @deck do |form| %>
	<%= render form %>
	<%= form.submit "Create Deck" %>
<% end %>
</div>

app/views/decks/show.html.erb
<h1><%= @deck.name %></h1>
<div class="actions">
	<%= link_to "<< Back to all decks", decks_path %> |
	<%= link_to "Create a new card", new_deck_card_path(@deck) %>
</div>
<div class="container">
<ul>
	<% @cards.each do |card| %>
		<li>
		<%= link_to card.front, [@deck, card] %> &mdash; 
		<%= link_to "Edit", edit_deck_card_path(@deck, card) %>
		<%= link_to "Delete", [@deck, card], data: { confirm: "Are you sure you want to delete this card?" }, method: :delete  %>
		</li>
	<% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlashcardsNovid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |f| %>
 <div class="flash <%= f[0] %>"><%= f[1] %></div>
<% end %>
<%= yield %>

</body>
</html>